on:
  push:
    branches:
      - stage
jobs:
  build:
    runs-on: docker
    #environment: ${{ env.FORGEJO_REF_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build

      - name: Deploy dist to dist-${{ env.FORGEJO_REF_NAME }}
        run: |
          git config user.name "forgejo-actions[bot]"
          git config user.email "forgejo-actions[bot]@users.noreply.local"

          git checkout --orphan temp
          git rm -rf .

          git add dist
          git commit -m "Update dist"

          git push \
            "https://x-access-token:${{ secrets.FORGEJO_TOKEN }}@git.workaround.org/${{ github.repository }}.git" \
            temp:dist-${{ env.FORGEJO_REF_NAME }} \
            --force

      # - name: Trigger deployment webhook
      #   env:
      #     DEPLOY_WEBHOOK: ${{ secrets.COOLIFY_STAGE_DEPLOY_WEBHOOK }}
      #     DEPLOY_TOKEN: ${{ secrets.COOLIFY_STAGE_DEPLOY_TOKEN }}
      #   run: |
      #     curl -v "$DEPLOY_WEBHOOK" \
      #       --header "Authorization: Bearer $DEPLOY_TOKEN"
